controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    tricycle_controller:
      type: tricycle_controller/TricycleController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    extra_joints: ["right_wheel_joint", "left_wheel_joint"]

tricycle_controller:
  ros__parameters:
    traction_joint_name: "front_wheel_joint"
    steering_joint_name: "bearing_joint"
    wheelbase: 0.975
    wheel_radius: 0.125

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    open_loop: false
    enable_odom_tf: true
    odom_only_twist: false
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    velocity_rolling_window_size: 10
    cmd_vel_timeout: 500
    publish_ackermann_command: true

    traction:
      max_velocity: 50.0
      max_acceleration: 10.0
      max_deceleration: 20.0
    steering:
      min_position: -1.4
      max_position: 1.4
      max_velocity: 3.0
      max_acceleration: 5.0
